#!/usr/bin/env bash
git fetch
git branch --set-upstream-to=origin/$(git symbolic-ref --short HEAD)
git pull
if [ -f ".gitmodules" ]; then
    git submodule sync --recursive
    git submodule update --recursive --init
fi
if [ -f ".gitfat" ]; then
    git fat submodule update --init --recursive
    git fat pull
fi

